project_id = "dvwmyljnssspwfpwocof"

[functions.fetch-stock-news]
verify_jwt = false

[functions.fetch-stock-data]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.create-payment]
verify_jwt = false